const plugin = require("tailwindcss/plugin");
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
    purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        screens: {
            xs: "350px",
            ...defaultTheme.screens,
        },
        extend: {
            colors: {
                yellow: {
                    "100-transparent": "#FEEDCE20",
                    "500-transparent": "#FEEDCE",
                    "700-transparent": "#C48D33",
                },
                blue: {
                    "100-transparent": "#ACF1FF20",
                    "300-transparent": "#ACF1FF50",
                    "500-transparent": "#ACF1FF",
                    "700-transparent": "#2C9BB5",
                },
                purple: {
                    "100-transparent": "#D5D4FF20",
                    "500-transparent": "#D5D4FF",
                    "700-transparent": "#605EB1",
                },
                orange: {
                    500: "#FE8A36",
                    "100-transparent": "#FE8A3610",
                },
            },
            fontFamily: {
                rubik: ["Rubik", "sans-serif"],
                roboto: ["Roboto", "sans-serif"],
            },
        },
    },
    variants: {
        accessibility: ["before", "after", "responsive", "focus-within", "focus"],
        alignContent: ["before", "after", "responsive"],
        alignItems: ["before", "after", "responsive"],
        alignSelf: ["before", "after", "responsive"],
        animation: ["before", "after", "responsive"],
        appearance: ["before", "after", "responsive"],
        backdropBlur: ["before", "after", "responsive"],
        backdropBrightness: ["before", "after", "responsive"],
        backdropContrast: ["before", "after", "responsive"],
        backdropFilter: ["before", "after", "responsive"],
        backdropGrayscale: ["before", "after", "responsive"],
        backdropHueRotate: ["before", "after", "responsive"],
        backdropInvert: ["before", "after", "responsive"],
        backdropOpacity: ["before", "after", "responsive"],
        backdropSaturate: ["before", "after", "responsive"],
        backdropSepia: ["before", "after", "responsive"],
        backgroundAttachment: ["before", "after", "responsive"],
        backgroundBlendMode: ["before", "after", "responsive"],
        backgroundClip: ["before", "after", "responsive"],
        backgroundColor: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        backgroundImage: ["before", "after", "responsive"],
        backgroundOpacity: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        backgroundPosition: ["before", "after", "responsive"],
        backgroundRepeat: ["before", "after", "responsive"],
        backgroundSize: ["before", "after", "responsive"],
        backgroundOrigin: ["before", "after", "responsive"],
        blur: ["before", "after", "responsive"],
        borderCollapse: ["before", "after", "responsive"],
        borderColor: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        borderOpacity: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        borderRadius: ["before", "after", "responsive"],
        borderStyle: ["before", "after", "responsive"],
        borderWidth: ["before", "after", "responsive"],
        boxDecorationBreak: ["before", "after", "responsive"],
        boxShadow: ["before", "after", "responsive", "group-hover", "focus-within", "hover", "focus"],
        boxSizing: ["before", "after", "responsive"],
        brightness: ["before", "after", "responsive"],
        clear: ["before", "after", "responsive"],
        container: ["before", "after", "responsive"],
        contrast: ["before", "after", "responsive"],
        cursor: ["before", "after", "responsive"],
        display: ["before", "after", "responsive"],
        divideColor: ["before", "after", "responsive", "dark"],
        divideOpacity: ["before", "after", "responsive", "dark"],
        divideStyle: ["before", "after", "responsive"],
        divideWidth: ["before", "after", "responsive"],
        dropShadow: ["before", "after", "responsive"],
        fill: ["before", "after", "responsive"],
        filter: ["before", "after", "responsive"],
        flex: ["before", "after", "responsive"],
        flexDirection: ["before", "after", "responsive"],
        flexGrow: ["before", "after", "responsive"],
        flexShrink: ["before", "after", "responsive"],
        flexWrap: ["before", "after", "responsive"],
        float: ["before", "after", "responsive"],
        fontFamily: ["before", "after", "responsive"],
        fontSize: ["before", "after", "responsive"],
        fontSmoothing: ["before", "after", "responsive"],
        fontStyle: ["before", "after", "responsive"],
        fontVariantNumeric: ["before", "after", "responsive"],
        fontWeight: ["before", "after", "responsive"],
        gap: ["before", "after", "responsive"],
        gradientColorStops: ["before", "after", "responsive", "dark", "hover", "focus"],
        grayscale: ["before", "after", "responsive"],
        gridAutoColumns: ["before", "after", "responsive"],
        gridAutoFlow: ["before", "after", "responsive"],
        gridAutoRows: ["before", "after", "responsive"],
        gridColumn: ["before", "after", "responsive"],
        gridColumnEnd: ["before", "after", "responsive"],
        gridColumnStart: ["before", "after", "responsive"],
        gridRow: ["before", "after", "responsive"],
        gridRowEnd: ["before", "after", "responsive"],
        gridRowStart: ["before", "after", "responsive"],
        gridTemplateColumns: ["before", "after", "responsive"],
        gridTemplateRows: ["before", "after", "responsive"],
        height: ["before", "after", "responsive"],
        hueRotate: ["before", "after", "responsive"],
        inset: ["before", "after", "responsive"],
        invert: ["before", "after", "responsive"],
        isolation: ["before", "after", "responsive"],
        justifyContent: ["before", "after", "responsive"],
        justifyItems: ["before", "after", "responsive"],
        justifySelf: ["before", "after", "responsive"],
        letterSpacing: ["before", "after", "responsive"],
        lineHeight: ["before", "after", "responsive"],
        listStylePosition: ["before", "after", "responsive"],
        listStyleType: ["before", "after", "responsive"],
        margin: ["before", "after", "responsive"],
        maxHeight: ["before", "after", "responsive"],
        maxWidth: ["before", "after", "responsive"],
        minHeight: ["before", "after", "responsive"],
        minWidth: ["before", "after", "responsive"],
        mixBlendMode: ["before", "after", "responsive"],
        objectFit: ["before", "after", "responsive"],
        objectPosition: ["before", "after", "responsive"],
        opacity: ["before", "after", "responsive", "group-hover", "focus-within", "hover", "focus"],
        order: ["before", "after", "responsive"],
        outline: ["before", "after", "responsive", "focus-within", "focus"],
        overflow: ["before", "after", "responsive"],
        overscrollBehavior: ["before", "after", "responsive"],
        padding: ["before", "after", "responsive"],
        placeContent: ["before", "after", "responsive"],
        placeItems: ["before", "after", "responsive"],
        placeSelf: ["before", "after", "responsive"],
        placeholderColor: ["before", "after", "responsive", "dark", "focus"],
        placeholderOpacity: ["before", "after", "responsive", "dark", "focus"],
        pointerEvents: ["before", "after", "responsive"],
        position: ["before", "after", "responsive"],
        resize: ["before", "after", "responsive"],
        ringColor: ["before", "after", "responsive", "dark", "focus-within", "focus"],
        ringOffsetColor: ["before", "after", "responsive", "dark", "focus-within", "focus"],
        ringOffsetWidth: ["before", "after", "responsive", "focus-within", "focus"],
        ringOpacity: ["before", "after", "responsive", "dark", "focus-within", "focus"],
        ringWidth: ["before", "after", "responsive", "focus-within", "focus"],
        rotate: ["before", "after", "responsive", "hover", "focus"],
        saturate: ["before", "after", "responsive"],
        scale: ["before", "after", "responsive", "hover", "focus"],
        sepia: ["before", "after", "responsive"],
        skew: ["before", "after", "responsive", "hover", "focus"],
        space: ["before", "after", "responsive"],
        stroke: ["before", "after", "responsive"],
        strokeWidth: ["before", "after", "responsive"],
        tableLayout: ["before", "after", "responsive"],
        textAlign: ["before", "after", "responsive"],
        textColor: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        textDecoration: ["before", "after", "responsive", "group-hover", "focus-within", "hover", "focus"],
        textOpacity: ["before", "after", "responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        textOverflow: ["before", "after", "responsive"],
        textTransform: ["before", "after", "responsive"],
        transform: ["before", "after", "responsive"],
        transformOrigin: ["before", "after", "responsive"],
        transitionDelay: ["before", "after", "responsive"],
        transitionDuration: ["before", "after", "responsive"],
        transitionProperty: ["before", "after", "responsive"],
        transitionTimingFunction: ["before", "after", "responsive"],
        translate: ["before", "after", "responsive", "hover", "focus"],
        userSelect: ["before", "after", "responsive"],
        verticalAlign: ["before", "after", "responsive"],
        visibility: ["before", "after", "responsive"],
        whitespace: ["before", "after", "responsive"],
        width: ["before", "after", "responsive"],
        wordBreak: ["before", "after", "responsive"],
        zIndex: ["before", "after", "responsive", "focus-within", "focus"],
        extend: {
            inset: ["group-hover"],
        },
    },
    plugins: [
        plugin(({ addVariant, e }) => {
            addVariant("before", ({ modifySelectors, separator }) => {
                modifySelectors(({ className }) => {
                    return `.${e(`before${separator}${className}`)}::before`;
                });
            });
            addVariant("after", ({ modifySelectors, separator }) => {
                modifySelectors(({ className }) => {
                    return `.${e(`after${separator}${className}`)}::after`;
                });
            });
        }),
        plugin(({ addUtilities }) => {
            const contentUtilities = {
                ".content": {
                    content: "attr(data-content)",
                },
                ".content-before": {
                    content: "attr(data-before)",
                },
                ".content-after": {
                    content: "attr(data-after)",
                },
            };

            addUtilities(contentUtilities, ["before", "after"]);
        }),
    ],
};
